### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by kuaikuaikim** [OAID/FaceDetection#1]
@xhbdahai i met a problem when i make your project,can you help me..
/usr/bin/ld: cannot find -larm_compute
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'test' failed

**Comment by cyberfire** [comment]
Close it since it has been resolved.

**Comment by arasharchor** [comment]
@cyberfire  @quickj @xhbdahai how did you solve it?
I am using Jetson TX1 and have this problem.

**Comment by arasharchor** [comment]
Okay. I was not using CaffeonACL.
