### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by kuaikuaikim** [OAID/FaceDetection#2]
i have disable the arm_compute, but met another problem whem make your project. I built the libmtcnn.so successfully. Link the test.a just print these problem below.

/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_DeleteTensor'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_DeleteStatus'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_DeleteSession'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_DeleteGraph'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_Message'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_TensorData'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewGraph'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewSessionOptions'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_SessionRun'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewSession'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_CloseSession'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_GraphOperationByName'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_GraphImportGraphDef'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewStatus'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_Dim'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewTensor'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_GetCode'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_NewImportGraphDefOptions'
/home/sg/workspace/mtcnn/libmtcnn/libmtcnn.so: undefined reference to `TF_ImportGraphDefOptionsSetPrefix'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by cyberfire** [comment]
As the pre-built libtensorflow.so is for arm64, and if you are trying this on x86,  ld will complain.

You can workaround this by two methods:
1) Skip tensorflow support by setting TF_ON=0
2)  Build  libtensorflow.so as guided in README.md

Thanks,

cyberfire

**Comment by cyberfire** [comment]
Please re-open if meet new issue

**Comment by flankechen** [comment]
Hi, I have the same problem. I follow this https://www.tensorflow.org/install/install_c for tensorflow c apis, but not bazel build. I do have libtensorflow.so in TENSORFLOW_ROOT. I guess I have to link it to test/camera.a as well?

**Comment by kapildevkumar** [comment]
Seems to be similar to [this](https://github.com/OAID/FaceDetection/issues/8) issue. The fix works like charm. I had to add the install library path to variable(LD_LIBRARY_PATH)
